services:
  - type: web
    name: greenavto
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist/client
    autoDeploy: true
    routes:
      - type: rewrite
        source: /privacy
        destination: /privacy.html
      - type: rewrite
        source: /privacy/
        destination: /privacy.html
      - type: rewrite
        source: /consent
        destination: /consent.html
      - type: rewrite
        source: /consent/
        destination: /consent.html
      - type: rewrite
        source: /*
        destination: /index.html
